"""The genre words a region may be called. Frozen on purpose.

Naming was the one place in this project where a model wrote free text, and it
was the one feature that drifted: 42 of 80 region names changed in a single
rebuild - "melodic trap" became "trap", "hip hop" became "mainstream rap". A
profile that says you are big in a genre should not quietly rename the genre.

It also let a measurement bias reach the user. Deezer is French, and French
artists carry roughly seven times the median fan count of American ones there,
so French rap won the exemplar ranking inside a large mixed rap region and the
model named that whole region "french rap" - over Kanye, J. Cole and Lil Wayne.
A word absent from this list cannot be chosen, so that class of leak is shut.

Derived rather than invented: every entry is a tag carried by at least 200 artists
in the corpus, minus three kinds of word that are not a sound -

  - judgements about the listener: best, underrated, essential, guilty pleasure
  - places: denmark, detroit, africa, south korea
  - moods and formats: chill, summer, workout, instrumental, live

- plus a few genuinely niche scenes sitting just under the cut, kept by hand,
because a frequency threshold cannot know that afrobeats is a genre and
"amazing" is not.

Changing this list is a migration, not a tweak: saved profiles refer to these
words. Adding is safe; removing or renaming is not.
"""

from __future__ import annotations

# 385 labels. Under 500 because that is the ceiling on enum values in a
# structured-output schema, and this is used as one.
GENRES: tuple[str, ...] = (
    "8 bit",
    "8bit",
    "abstract hip hop",
    "acid",
    "acid house",
    "acid jazz",
    "afrobeat",
    "afrobeats",
    "aggrotech",
    "alt country",
    "alternative",
    "alternative hip hop",
    "alternative metal",
    "alternative pop",
    "alternative rap",
    "alternative rnb",
    "alternative rock",
    "amapiano",
    "ambient",
    "ambient techno",
    "anime",
    "aor",
    "arabic",
    "art pop",
    "art rock",
    "asian music",
    "asian pop",
    "atmospheric black metal",
    "atmospheric drum and bass",
    "avant garde",
    "avant garde jazz",
    "avantgarde",
    "ballad",
    "baroque",
    "bebop",
    "bedroom pop",
    "big band",
    "black metal",
    "blackened death metal",
    "bluegrass",
    "blues",
    "blues rock",
    "boom bap",
    "bossa nova",
    "breakbeat",
    "breakcore",
    "britpop",
    "broadway",
    "brostep",
    "brutal death metal",
    "c pop",
    "cabaret",
    "celtic",
    "chanson",
    "chanson francaise",
    "chill house",
    "chill out",
    "chiptune",
    "choral",
    "christian",
    "christian rock",
    "classical",
    "cloud rap",
    "coldwave",
    "comedy",
    "contemporary christian",
    "contemporary classical",
    "contemporary jazz",
    "country",
    "country rock",
    "crust",
    "cumbia",
    "dance pop",
    "dancehall",
    "dark ambient",
    "dark electro",
    "darkstep",
    "darkwave",
    "death metal",
    "deathcore",
    "deep house",
    "depressive black metal",
    "deutschrap",
    "dirty south",
    "disco",
    "djent",
    "dnb",
    "doom",
    "doom metal",
    "doujin ongaku",
    "downtempo",
    "dream pop",
    "drill",
    "drone",
    "drum & bass",
    "drum and bass",
    "drum n bass",
    "drum'n'bass",
    "dub",
    "dub techno",
    "dubstep",
    "dungeon synth",
    "early music",
    "east coast hip hop",
    "east coast rap",
    "easy listening",
    "ebm",
    "edm",
    "electro",
    "electro house",
    "electro industrial",
    "electroclash",
    "electronic",
    "electronica",
    "electropop",
    "emo",
    "emo rap",
    "emocore",
    "eurobeat",
    "eurodance",
    "eurovision",
    "eurovision song contest",
    "experimental",
    "experimental hip hop",
    "experimental rock",
    "finnish",
    "finnish metal",
    "folk",
    "folk metal",
    "folk pop",
    "folk punk",
    "folk rock",
    "footwork",
    "freak folk",
    "free improvisation",
    "free jazz",
    "french rap",
    "funk",
    "funky",
    "fusion",
    "future bass",
    "future garage",
    "futurepop",
    "gabber",
    "game music",
    "gangsta rap",
    "garage",
    "garage punk",
    "garage rock",
    "glam metal",
    "glam rock",
    "glitch",
    "glitch hop",
    "gospel",
    "goth",
    "gothic",
    "gothic metal",
    "gothic rock",
    "grime",
    "grindcore",
    "groove metal",
    "grunge",
    "guitar virtuoso",
    "hair metal",
    "happy hardcore",
    "hard bop",
    "hard rock",
    "hard techno",
    "hard trance",
    "hardcore",
    "hardcore punk",
    "hardcore rap",
    "hardcore techno",
    "hardstyle",
    "harsh ebm",
    "heavy metal",
    "hip hop",
    "hiphop",
    "horrorcore",
    "house",
    "hyperpop",
    "idm",
    "indie",
    "indie folk",
    "indie pop",
    "indie rock",
    "indietronica",
    "industrial",
    "industrial metal",
    "industrial rock",
    "industrial techno",
    "instrumental hip hop",
    "instrumental rock",
    "italo disco",
    "j pop",
    "j rock",
    "jangle pop",
    "japanese",
    "jazz",
    "jazz funk",
    "jazz fusion",
    "jazz hop",
    "jazz piano",
    "jazz rock",
    "jazz vocal",
    "jersey club",
    "jpop",
    "jrock",
    "jungle",
    "k pop",
    "korean",
    "kpop",
    "krautrock",
    "latin jazz",
    "latin pop",
    "liquid funk",
    "lo fi",
    "lofi",
    "lounge",
    "mashup",
    "math rock",
    "mathcore",
    "medieval",
    "meditation",
    "melodic black metal",
    "melodic death metal",
    "melodic hardcore",
    "melodic metal",
    "melodic metalcore",
    "melodic rock",
    "melodic trance",
    "metal",
    "metalcore",
    "mexican",
    "midwest emo",
    "minimal synth",
    "minimal techno",
    "minimal wave",
    "minimalism",
    "modern classical",
    "modern country",
    "modern rock",
    "motown",
    "mpb",
    "neo psychedelia",
    "neo soul",
    "neoclassical",
    "neofolk",
    "neurofunk",
    "new age",
    "new wave",
    "nigerian",
    "noise",
    "noise pop",
    "noise rock",
    "northern soul",
    "norwegian",
    "nu disco",
    "nu jazz",
    "nu metal",
    "old school death metal",
    "old school hardcore",
    "oldies",
    "opera",
    "orchestral",
    "phonk",
    "plugg",
    "pop",
    "pop punk",
    "pop rap",
    "pop rock",
    "post bop",
    "post grunge",
    "post hardcore",
    "post industrial",
    "post metal",
    "post punk",
    "post rock",
    "power metal",
    "power pop",
    "powerpop",
    "progressive",
    "progressive death metal",
    "progressive house",
    "progressive metal",
    "progressive rock",
    "progressive trance",
    "psychedelic",
    "psychedelic folk",
    "psychedelic pop",
    "psychedelic rock",
    "psychedelic trance",
    "psychill",
    "psytrance",
    "punk",
    "punk rock",
    "r&b",
    "ragga",
    "rap",
    "rapcore",
    "raw black metal",
    "real screamo",
    "reggae",
    "reggaeton",
    "renaissance",
    "retrowave",
    "rhythm and blues",
    "rhythmic noise",
    "rnb",
    "rock",
    "rock and roll",
    "rock n roll",
    "rockabilly",
    "rocksteady",
    "roots reggae",
    "russian rap",
    "russian rock",
    "salsa",
    "samba",
    "schlager",
    "screamo",
    "sea shanties",
    "shoegaze",
    "singer songwriter",
    "ska",
    "ska punk",
    "skramz",
    "slowcore",
    "sludge",
    "sludge metal",
    "smooth jazz",
    "soft rock",
    "soul",
    "soundscape",
    "south african",
    "southern hip hop",
    "southern rap",
    "southern rock",
    "space ambient",
    "space rock",
    "spanish",
    "speed metal",
    "speedcore",
    "spoken word",
    "stoner",
    "stoner metal",
    "stoner rock",
    "straight edge",
    "surf",
    "surf rock",
    "swing",
    "symphonic metal",
    "synth pop",
    "synthpop",
    "synthwave",
    "tech house",
    "technical death metal",
    "techno",
    "techstep",
    "teen pop",
    "thrash",
    "thrash metal",
    "touhou",
    "trance",
    "trap",
    "trip hop",
    "turkish",
    "twee",
    "uk garage",
    "uk hip hop",
    "uplifting trance",
    "vaporwave",
    "video game",
    "video game music",
    "visual kei",
    "vocal house",
    "vocal jazz",
    "vocal trance",
    "vocaloid",
    "west coast rap",
    "witch house",
    "wonky",
    "world fusion",
    "world music",
    "worship",
)
